[parity]
chain = "dev"

[network]
warp = true

[ui]
force = false
disable = false
port = 8180
interface = "0.0.0.0"

[rpc]
disable = false
port = 8545
interface = "0.0.0.0"
hosts = ["all"]
apis = ["web3", "eth", "net", "personal", "parity", "parity_accounts", "parity_set", "signer", "traces", "rpc"]

[ipc]
disable = true

[dapps]
disable = false
port = 8080
interface = "0.0.0.0"
hosts = ["all"]

